# Generated by Django 5.0 on 2026-02-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='A URL-friendly version of the model instance name.', unique=True, verbose_name='URL Slug')),
                ('name', models.CharField(help_text='The name of the category. Must be unique.', max_length=100, unique=True, verbose_name='Category Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(help_text='The content of the comment.', verbose_name='Comment Content')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('slug', models.SlugField(help_text='A URL-friendly version of the model instance name.', unique=True, verbose_name='URL Slug')),
                ('title', models.CharField(help_text='The title of the blog post.', max_length=200, verbose_name='Post Title')),
                ('body', models.TextField(help_text='The content of the blog post.', verbose_name='Post Content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text="The status of the blog post. Can be 'draft', 'published', or 'archived'.", max_length=20, verbose_name='Post Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='A URL-friendly version of the model instance name.', unique=True, verbose_name='URL Slug')),
                ('name', models.CharField(help_text='The name of the tag. Must be unique.', max_length=50, unique=True, verbose_name='Tag Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
