# Generated by Django 5.0 on 2026-02-16 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(help_text='The author of the comment. If the author is deleted, the comment will also be deleted.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='The author of the blog post. If the author is deleted, the post will also be deleted.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The category associated with this blog post. Can be null if the category is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(help_text='The blog post that this comment is associated with. If the post is deleted, the comment will also be deleted.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags associated with this blog post. A post can have multiple tags.', related_name='posts', to='blog.tags', verbose_name='Tags'),
        ),
    ]
