# Generated by Django 5.0 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="name_en",
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The category name in Russian.",
                max_length=100,
                verbose_name="Category name (Russian)",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_kk",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The category name in Kazakh.",
                max_length=100,
                verbose_name="Category name (Kazakh)",
            ),
        ),
    ]

