# Generated by Django 5.0 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_category_i18n_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                help_text="The category name in English.",
                max_length=100,
                unique=True,
                verbose_name="Category name (English)",
            ),
        ),
    ]

