# Generated by Django 5.0 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_category_name_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                help_text="The status of the blog post. Can be 'draft', 'published', or 'archived'.",
                max_length=20,
                verbose_name="Post Status",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The moment the post first became published.",
                null=True,
                verbose_name="Published At",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a scheduled post should be automatically published.",
                null=True,
                verbose_name="Publish At",
            ),
        ),
    ]
