# Generated by Django 5.0 on 2026-03-14

from django.db import migrations, models

import apps.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_language",
            field=models.CharField(
                default="en",
                help_text="Choose your preferred language.",
                max_length=8,
                validators=[apps.users.validators.validate_preferred_language],
                verbose_name="preferred language",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Choose your timezone (IANA identifier).",
                max_length=64,
                validators=[apps.users.validators.validate_iana_timezone],
                verbose_name="timezone",
            ),
        ),
    ]

